課題９のコードと実行結果
riotakenouchi/C_charenge pull request #12
Opened 2024-08-21 06:10 UTC by riotakenouchi

int型の2つの変数の値を入れ替える
関数を作成してください。 
出力例：void swap_int(int *a, int *b);

2024-08-21 06:17 UTC, ShunsukeNakamura2 requested changes

2024-08-21 06:17 UTC, ShunsukeNakamura2 commented on exercise9/practice_9.c
> +void swap_int(int *a, int *b);
課題7と同様の指摘があります
確認してください

2024-08-21 06:17 UTC, ShunsukeNakamura2 commented on exercise9/practice_9.c
> +void swap_int(int *a, int *b) {
関数定義の { は改行をしてください

2024-08-21 06:17 UTC, ShunsukeNakamura2 commented on exercise9/practice_9.c
> +/*値を入れ替える関数の定義*/
doxygenで関数コメントを作成してください

2024-08-21 06:17 UTC, ShunsukeNakamura2 commented on exercise9/practice_9.c
> +
細かいですが、改行は1つで十分だと思います。

2024-08-22 00:39 UTC, ShotaNagao commented on exercise9/practice_9.c
> +void swap_int(int *a, int *b) {
int *a, int *bは何のための変数かぱっと見で分からないです。
こういう2変数間の入れ替えのためだったり、比較のための変数名で多いのは、右手と左手の意味のlhs,rhsが多いと思います。

2024-08-22 00:39 UTC, ShotaNagao commented on exercise9/practice_9.c
> +void swap_int(int *a, int *b) {
ロジック上はこの書き方が正解です。
下記に過去の研修で頂いたコメントで別解をもらっていたのでそちら記載いたします。

以下過去コメント
【教えてもらったこと】
たまに以下のような書き方をする人がいるので(うちの会社でやると多分レビューで指摘されるけど)覚えておいてください。知らないと面食らうので。

void swap_int(int *n1, int *n2)
{
　if (*n1 == *n2) {
　　return;
　}
　*n1 ^= *n2;
　*n2 ^= *n1;
　*n1 ^= *n2;
}

このやり方は、関数マクロにすることで、引数部分がint以外の場合でも適用できるので好んで使う人たちが世の中にはいます。
ただ、いかんせん読みにくくなるため、うちの会社では推奨されてないです(多分)し、製品コードでは見たことないですね。
関数マクロにすればのところはこんな感じ

#define swap(a, b) ((a) ^= (b); (b) ^= (a); (a) ^= (b);)

こう書くと引数がintでもdoubleでもcharでも構造体でも動きます。
古の黒魔法使いなどはこういう事をしますが、最近はやる人いないと思います。。
XOR交換アルゴリズムは、最近のCPUではこのやり方よりも普通に一時変数を使用した方がコンパイラ最適化によって早くなるので、正直このやり方をやるメリットは今の時代は1つもないみたいです。

2024-08-22 05:56 UTC, ShunsukeNakamura2 requested changes

2024-08-22 05:56 UTC, ShunsukeNakamura2 commented on exercise9/practice_9.c
> + * この関数は、2つの整数のポインタを受け取り、これらの値を入れ替えます。
```
@details 値を入れ替える関数
         この関数は、2つの整数のポインタを受け取り、これらの値を入れ替えます。
```
や
```
@details 値を入れ替える関数
@note    この関数は、2つの整数のポインタを受け取り、これらの値を入れ替えます。
```
のように書くと良いと思います。これも課題7で指摘しているはず。

2024-08-22 05:56 UTC, ShunsukeNakamura2 commented on exercise9/practice_9.c
> + * @param a 値を入れ替える整数へのポインタ
```
@param[in]
@param[out]
@param[in,out]
```
これを使用するとより良いです

2024-08-22 05:57 UTC, ShunsukeNakamura2 commented on exercise9/practice_9.c
> +void swap_int(int *a, int *b) {
指摘に答えてないのに会話閉じたらだめでは？

2024-08-22 05:58 UTC, ShotaNagao commented on exercise9/practice_9.c
> +static void swap_int(int *a, int *b)
int *a, int *bは何のための変数かぱっと見で分からないです。
こういう2変数間の入れ替えのためだったり、比較のための変数名で多いのは、右手と左手の意味のlhs,rhsが多いと思います。

2024-08-22 06:01 UTC, ShotaNagao commented on exercise9/practice_9.c
> +void swap_int(int *a, int *b) {
私が誤操作で閉じてしましました！
ただ、最新のソースでも治ってなさそうだったので同じ指摘を同じ個所に再度し直しています。

2024-08-22 06:04 UTC, ShunsukeNakamura2 commented on exercise9/practice_9.c
> +void swap_int(int *a, int *b) {
@ShotaNagao 
そうだったんですね、了解です。
@riotakenouchi 
失礼しました。

2024-08-22 07:55 UTC, riotakenouchi commented on exercise9/practice_9.c
> +static void swap_int(int *a, int *b)
問題文で扱う関数，変数が指定されているからです。

2024-08-22 07:55 UTC, riotakenouchi commented on exercise9/practice_9.c
> + * この関数は、2つの整数のポインタを受け取り、これらの値を入れ替えます。
修正しました。

2024-08-22 07:56 UTC, riotakenouchi commented on exercise9/practice_9.c
> + * @param a 値を入れ替える整数へのポインタ
ありがとうございます。

2024-08-22 08:15 UTC, ShunsukeNakamura2 approved these changes

2024-08-22 08:18 UTC, ShotaNagao commented on exercise9/practice_9.c
> +static void swap_int(int *a, int *b)
問題文に書いてありました。すみませんOKです。

2024-08-22 08:20 UTC, ShotaNagao approved these changes

2024-08-22 08:20 UTC, merged