課題10のコードと実行結果
riotakenouchi/C_charenge pull request #13
Opened 2024-08-26 06:14 UTC by riotakenouchi

下記構造体の配列をソートし表示してください。
ソート順は、nの値で昇順、nが同一の値の
場合はsの文字コードで昇順とします。
ソート処理にはC標準関数qsort()を使ってください。

構造体と配列
typedef struct DAT_t {
       int n;
       const char* s;
} DAT;
DAT dat[] = {
       {9, "A"},
       {2, "A"},
       {5, "AB"},
       {5, "AA"},
};

2024-08-26 06:59 UTC, ShunsukeNakamura2 requested changes

2024-08-26 06:59 UTC, ShunsukeNakamura2 commented on exercise10/practice_10.c
> +static int compare(const void *a, const void *b)
プロトタイプ宣言を使用してください

2024-08-26 06:59 UTC, ShunsukeNakamura2 commented on exercise10/practice_10.c
> +/** @brief 比較関数
改行して@briefを始めると、下と揃って良いと思います

2024-08-26 06:59 UTC, ShunsukeNakamura2 commented on exercise10/practice_10.c
> +static int compare(const void *a, const void *b)
DATを比較していると分かる名前にしてください

2024-08-26 06:59 UTC, ShunsukeNakamura2 commented on exercise10/practice_10.c
```
DAT dat[] =
 {
    {9, "A"},
    {-2147483647, "A"},
    {5, "AB"},
    {5, "AA"},
};
```
試しにこれを比較してみてください。
思った通りの結果にならないはず

2024-08-26 06:59 UTC, ShunsukeNakamura2 commented on exercise10/practice_10.c
> +    int n;                /**< 整数の値 */
特に情報を持たないコメントなので、不要かなと思います

2024-08-26 06:59 UTC, ShunsukeNakamura2 commented on exercise10/practice_10.c
> + * @param[in,out] a 比較する最初の要素
中で書き換えが起こるわけでもないので、outの要素は持たないと思います。
「入力として渡すだけで、関数内で書き換えは起きません。安心して渡してください。」という意味でconstが付いてます。

2024-08-26 06:59 UTC, ShunsukeNakamura2 commented on exercise10/practice_10.c
> + * @return 整数 比較結果
これだと、比較した結果何が返ってくるのかを確認するために、コードを読みに来る必要があります。
doxygenだけ見てこの関数を使えるようになるのが理想です。

2024-08-26 08:51 UTC, ShotaNagao commented on exercise10/practice_10.c
> +    size_t size = sizeof(dat) / sizeof(dat[0]);
変数の宣言と処理はなるべく分けて欲しいです。

2024-08-26 08:51 UTC, ShotaNagao commented on exercise10/practice_10.c
> +    size_t size = sizeof(dat) / sizeof(dat[0]);
①この変数名だと何のサイズを表しているか分からない(構造体全体？メンバのサイズ？その他のサイズ？)
②サイズという名前が不適切。(この変数に入っているのはメンバの個数（要素数）であってサイズではない)

2024-08-27 08:35 UTC, riotakenouchi commented on exercise10/practice_10.c
> +static int compare(const void *a, const void *b)
宣言を追加しました。

2024-08-27 08:35 UTC, riotakenouchi commented on exercise10/practice_10.c
> +/** @brief 比較関数
下に改行しました。

2024-08-27 08:36 UTC, riotakenouchi commented on exercise10/practice_10.c
> +static int compare(const void *a, const void *b)
compare_DATという変数名に変更しました。

2024-08-27 08:37 UTC, riotakenouchi commented on exercise10/practice_10.c
returnで返す数値を変更して正しくソートできることを確認しました。

2024-08-27 08:37 UTC, riotakenouchi commented on exercise10/practice_10.c
> +    int n;                /**< 整数の値 */
削除しました。

2024-08-27 08:38 UTC, riotakenouchi commented on exercise10/practice_10.c
> + * @param[in,out] a 比較する最初の要素
変更しました。

2024-08-27 08:38 UTC, riotakenouchi commented on exercise10/practice_10.c
> + * @return 整数 比較結果
return文の内容を変更しました。

2024-08-27 08:38 UTC, riotakenouchi commented on exercise10/practice_10.c
> +    size_t size = sizeof(dat) / sizeof(dat[0]);
初期化処理を行いました。

2024-08-27 08:39 UTC, riotakenouchi commented on exercise10/practice_10.c
> +    size_t size = sizeof(dat) / sizeof(dat[0]);
num_elementという変数名に変更しました。

2024-08-27 09:03 UTC, ShotaNagao commented on exercise10/practice_10.c
> +static int compare_DAT(const void *a, const void *b)
これ引数の型がvoidである必要はありますか？
関数の名前的にDAT構造体の比較であることは分かるので引数もDAT型でもいいのでは？
多分他の人がこの関数を転用しようとしても、DAT構造体以外の比較に使おうとは思わない関数名なので、拡張性はあまり意識しないでいいと思います。

2024-08-27 09:03 UTC, ShotaNagao commented on exercise10/practice_10.c
> +    DAT *datB = (DAT *)b;
引数がDAT型でない場合は必要な処理ですが、そうでないなら不要な変数かと思います。

2024-08-27 09:03 UTC, ShotaNagao commented on exercise10/practice_10.c
> + * @brief 比較関数
コメントで説明しているのに処理が遠いと説明の意味が薄れると思います。
コメントはできれば実際の処理が書いてある場所に書いてもらいたいです。
(今回のソースでいうと53行目などに)

2024-08-27 09:03 UTC, ShotaNagao commented on exercise10/practice_10.c
> +/** @brief メイン関数
@ShunsukeNakamura2 
main関数のコメントっていると思います？
個人的にmain関数にコメントが記載されているソースを見たことがないので意見を伺いたいです。

2024-08-27 09:03 UTC, ShotaNagao commented on exercise10/practice_10.c
> +    size_t num_element = 0;/*初期化処理を定義*/
コメント部分の話しなので修正の必要はないですが、宣言部分でコメントするのは変数の機能について説明する場合がほとんどです。
初期化処理はわざわざコメントしなくていいと思います。
(宣言部分ではなく、処理の中で初期化をする場合はその処理のところでコメントしてください)

2024-08-27 22:50 UTC, ShunsukeNakamura2 commented on exercise10/practice_10.c
> +static int compare_DAT(const void *a, const void *b)
voidである必要があります。具体的にはqsort()に渡す比較関数は、以下の形式が指定されていて、違反するとwarningが出ます。
int (*)(const void *, const void *)

2024-08-27 22:57 UTC, ShunsukeNakamura2 commented on exercise10/practice_10.c
> +/** @brief メイン関数
自分も見たことが無かったので、HULFTのソースを見に行ったのですが、一つ見つけました。
https://github.com/saison-product/HULFT/blob/develop/common/src/utl/src/utlopllist.c
製品に存在しているのでOKとしてました。今回の課題くらいの規模で、ファイルが複数に分かれているわけでもないので、なくてもいいとは思います。

2024-08-27 23:02 UTC, ShunsukeNakamura2 requested changes

2024-08-27 23:02 UTC, ShunsukeNakamura2 commented on exercise10/practice_10.c
> + * @param a 比較する最初の要素
outの要素は無いと指摘しましたが、inの要素もないという判断でinも消しました？

2024-08-27 23:02 UTC, ShunsukeNakamura2 commented on exercise10/practice_10.c
> +{
この { は改行不要です

2024-08-27 23:02 UTC, ShunsukeNakamura2 commented on exercise10/practice_10.c
> +    {
この { は改行不要です

2024-08-28 00:34 UTC, ShotaNagao commented on exercise10/practice_10.c
> +static int compare_DAT(const void *a, const void *b)
qsortの仕様上のと理解しました。
関連のコメントも閉じときます。

2024-08-28 00:34 UTC, ShotaNagao commented on exercise10/practice_10.c
> +    DAT *datB = (DAT *)b;
同上

2024-08-28 00:40 UTC, ShotaNagao commented on exercise10/practice_10.c
> +/** @brief メイン関数
ご意見ありがとうございます。

【武ノ内さん向けに】
main関数へのコメントはそれほど多くないという事を認識してください。
返信等は必要ないので確認次第、resolveしてください。

2024-08-28 02:35 UTC, riotakenouchi commented on exercise10/practice_10.c
> +    {
修正しました。

2024-08-28 02:35 UTC, riotakenouchi commented on exercise10/practice_10.c
> +{
修正しました。

2024-08-28 02:37 UTC, riotakenouchi commented on exercise10/practice_10.c
> + * @param a 比較する最初の要素
outの要素がないならinを定義せずに扱う変数だけの説明をしてみようとしていました。
inの要素を加え変数を説明するように変更しました。

2024-08-28 02:38 UTC, riotakenouchi commented on exercise10/practice_10.c
> +    size_t num_element = 0;/*初期化処理を定義*/
承知しました。初期化処理のコメントを削除しました。

2024-08-28 02:39 UTC, riotakenouchi commented on exercise10/practice_10.c
> + * @brief 比較関数
関数が使われている部分の上部にコメントを移動させました。

2024-08-28 02:49 UTC, ShotaNagao commented on exercise10/practice_10.c
> +    DAT dat[] ={
=　の後ろに半角スペースを入れてください。

2024-08-28 03:07 UTC, ShunsukeNakamura2 requested changes

2024-08-28 03:07 UTC, ShunsukeNakamura2 commented on exercise10/practice_10.c
> +/** @brief メイン関数
ここのbriefも改行されると下と揃って良いです。
指摘があった時は、他にも該当箇所がないか確認をお願いします。

2024-08-28 03:12 UTC, riotakenouchi commented on exercise10/practice_10.c
> +    DAT dat[] ={
修正しました。

2024-08-28 03:13 UTC, riotakenouchi commented on exercise10/practice_10.c
> +/** @brief メイン関数
承知しました。

2024-08-28 03:18 UTC, ShotaNagao approved these changes

2024-08-28 03:31 UTC, ShunsukeNakamura2 requested changes

2024-08-28 03:31 UTC, ShunsukeNakamura2 commented on exercise10/practice_10.c
> +    DAT *datB = (DAT *)b;
datAとdatBにもconstを付けることで、不意の値書き換えを防止できます。

2024-08-28 03:46 UTC, riotakenouchi commented on exercise10/practice_10.c
> +    DAT *datB = (DAT *)b;
ありがとうございます。

2024-08-28 04:02 UTC, ShunsukeNakamura2 approved these changes

2024-08-29 06:43 UTC, Ryusei-Ami requested changes
ロジック的には問題ありません。細かい指摘のみです。
腑に落ちない点がある場合は、Slackで御質問下さい。

2024-08-29 06:43 UTC, Ryusei-Ami commented on exercise10/practice_10.c
> +    for (size_t i = 0; i < num_element; i++) {
for文の()内の変数宣言は、UNIX系のコンパイラでエラーになる場合があるので、()の外で宣言して下さい。

2024-08-29 06:43 UTC, Ryusei-Ami commented on exercise10/practice_10.c
> +    size_t num_element = 0;
好みの問題ではあるのですが、変数名はnum_datみたいに「なんの数」であるかが判るようにしたほうが可読性が上がります。
少なくともnum_elementは「要素ってどの要素？？」ってなるので、変数名を見ただけで「datの数っぽい」と判るnum_datの方が良いです。

2024-08-29 06:43 UTC, Ryusei-Ami commented on exercise10/practice_10.c
> + * @note 2つの DAT 構造体を比較し、qsort で使用するための関数。
説明が少しおかしい？
「qsort でDAT 構造体を比較するための関数」では？

2024-08-29 06:43 UTC, Ryusei-Ami commented on exercise10/practice_10.c
> + * @return 整数 比較結果 (負の値: datA < datB, 0: datA == datB, 正の値: datA > datB)
datA、datBは関数内の変数名なので、関数の説明では引数のa, bを使う方が良い。

2024-08-29 06:43 UTC, Ryusei-Ami commented on exercise10/practice_10.c
> +    } else {
elseにしなくてもよいのでは？

2024-08-29 06:43 UTC, Ryusei-Ami commented on exercise10/practice_10.c
> + * @brief メイン関数
「@brief DAT 構造体の配列をソートして表示します。」で良いのでは？
main()がメイン関数なのは自明なので。

2024-09-02 04:52 UTC, riotakenouchi commented on exercise10/practice_10.c
> +    for (size_t i = 0; i < num_element; i++) {
for文()外で宣言し直しました。

2024-09-02 04:52 UTC, riotakenouchi commented on exercise10/practice_10.c
> +    size_t num_element = 0;
num_elementからnum_datに変更しました。

2024-09-02 04:52 UTC, riotakenouchi commented on exercise10/practice_10.c
> + * @note 2つの DAT 構造体を比較し、qsort で使用するための関数。
修正しました。

2024-09-02 04:53 UTC, riotakenouchi commented on exercise10/practice_10.c
> + * @return 整数 比較結果 (負の値: datA < datB, 0: datA == datB, 正の値: datA > datB)
修正しました。

2024-09-02 04:53 UTC, riotakenouchi commented on exercise10/practice_10.c
> +    } else {
修正しました。

2024-09-02 04:53 UTC, riotakenouchi commented on exercise10/practice_10.c
> + * @brief メイン関数
メイン関数のコメントを削除しました。

2024-09-02 08:01 UTC, Ryusei-Ami requested changes

2024-09-02 08:01 UTC, Ryusei-Ami commented on exercise10/practice_10.c
> +    size_t i; /*変数宣言*/
昨今のコンパイラはこれでもコンパイル出来てしまったりしますが、弊社の開発ではNGです。
基準は「UNIX系でもコンパイル出来ること」です。個々のUNIX系のコーディングルールを学ぶ必要はなくて、従来のC言語コーディングルールに沿っていれば問題ないソースがかけるとの認識です。

良い機会なので、一次レビューワーの方から変数の宣言箇所の OK/NG ルールを教えてもらって下さい。

修正する際に、回答コメントとして、簡潔にOKのルールを記載お願いします。

2024-09-03 03:23 UTC, riotakenouchi commented on exercise10/practice_10.c
> +    size_t i; /*変数宣言*/
OK
・ブロック内
    → ブロックの先頭
・グローバル変数
    → 関数定義の外(グローバル変数の定義からしてそれはそう)
NG
・ブロックの処理途中での宣言

上記のように伺いました。

2024-09-03 03:57 UTC, Ryusei-Ami approved these changes
コメントの回答内容含め、OKです。
補足ですが、変数iのような変数の宣言は「size_t i;」のように、初期化しないで使うケースの方が多いです。理由は以下になります。
・ for文で必ず初期化される（使う直前で必ず初期化される）。
・ 変数宣言後、最初に初期化＆使用する間に、この変数を使用する箇所がない
もちろん初期化しても問題ありません。

2024-09-03 04:38 UTC, merged