課題11のコードと実行結果
riotakenouchi/C_charenge pull request #14
Opened 2024-09-02 05:25 UTC by riotakenouchi

コマンドラインで指定されたテキストファイルの
内容を表示するプログラムを作成してください。
(文字コード以外のコードが含まれていた
場合のことを考慮する必要はありません)

usage
usage: プログラム名 filename

2024-09-02 06:30 UTC, ShunsukeNakamura2 requested changes

2024-09-02 06:30 UTC, ShunsukeNakamura2 commented on exercise11/result11.txt
> +usage: ./display_file filename
通常usageに「./」は入らないです。
実行ファイル名は固定で決め打ちして良いです。

2024-09-02 06:30 UTC, ShunsukeNakamura2 commented on exercise11/result11.txt
> +usage: ./display_file filename
テキストファイルの内容を表示している実行結果を追加してください

2024-09-02 07:22 UTC, ShotaNagao commented on exercise11/practice_11.c
> +    FILE *file_pointer;
通例ファイルポインタはfp表記がほとんどなので、ここでもfpでいいです。

2024-09-02 07:22 UTC, ShotaNagao commented on exercise11/practice_11.c
> +    const char *input_filename = argv[1];
ここで宣言した意図はありますか？

2024-09-04 01:50 UTC, riotakenouchi commented on exercise11/result11.txt
> +usage: ./display_file filename
修正しました。

2024-09-04 01:50 UTC, riotakenouchi commented on exercise11/result11.txt
> +usage: ./display_file filename
追加しました。

2024-09-04 01:50 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    FILE *file_pointer;
修正しました。

2024-09-04 01:52 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    const char *input_filename = argv[1];
特にありません。

2024-09-04 02:29 UTC, ShunsukeNakamura2 requested changes

2024-09-04 02:29 UTC, ShunsukeNakamura2 commented on exercise11/practice_11.c
> +    const char *input_filename = argv[1];
変数宣言はブロックの先頭で行って下さい

2024-09-04 02:29 UTC, ShunsukeNakamura2 commented on exercise11/practice_11.c
> +        fprintf(stderr, "usage\nusage: display_file filename\n", argv[0]);
, argv[0]は不要では？

2024-09-04 02:29 UTC, ShunsukeNakamura2 commented on exercise11/practice_11.c
> +    int character;
char型が適切だと思いますが、intにしている理由がありますか？

2024-09-04 02:29 UTC, ShunsukeNakamura2 commented on exercise11/practice_11.c
> +    while ((character = fgetc(file_pointer)) != EOF) {
1文字ずつ読んで書いてはさすがに効率が悪いので、fgets()を使用したやり方に書き直して欲しいです

2024-09-04 02:29 UTC, ShunsukeNakamura2 commented on exercise11/practice_11.c
> +    fclose(file_pointer); /* 変数名を file_pointer に変更 */
fclose()も失敗する可能性があります。

2024-09-04 02:29 UTC, ShunsukeNakamura2 commented on exercise11/practice_11.c
> +    fclose(file_pointer); /* 変数名を file_pointer に変更 */
このレベルの変更をコメントに残す必要はないです。
基本的に変更履歴はgitで管理します。

2024-09-04 02:29 UTC, ShunsukeNakamura2 commented on exercise11/result11.txt
> +usage
問題文に書いてあったからだと思いますが、ここのusageは不要です。
同じこと2回言うことになるので。

2024-09-04 02:29 UTC, ShunsukeNakamura2 commented on exercise11/result11.txt
> +$ echo -e "こんにちは、これはサンプルテキストファイルです。\nこのファイルはcプログラムで表示されます。
なぜここでecho?

2024-09-04 02:29 UTC, ShunsukeNakamura2 commented on exercise11/result11.txt
> +<テキストファイル実行結果>
<テキストファイル実行結果>
はよく分からないです。
こちらもコード実行結果では？

2024-09-04 03:18 UTC, ShotaNagao commented on exercise11/practice_11.c
> +    FILE *file_pointer;
修正しましたか？

2024-09-04 03:34 UTC, ShotaNagao commented
今回はファイルの内容を表示するプログラムなので、表示した実ファイルもgit hubにあげてください。
実ファイルをあげてもらうことで実行結果の証跡にもなるので、よろしくお願いいたします。

2024-09-04 05:38 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    const char *input_filename = argv[1];
承知いたしました。

2024-09-04 05:38 UTC, riotakenouchi commented on exercise11/practice_11.c
> +        fprintf(stderr, "usage\nusage: display_file filename\n", argv[0]);
修正しました。

2024-09-04 05:40 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    int character;
特にありません。characterなのでchar型で定義するところを誤ってintで定義してしまい、そのままコンパイルまで通ってしまったため修正を怠ってしまっていました。

2024-09-04 05:40 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    while ((character = fgetc(file_pointer)) != EOF) {
修正しました。

2024-09-04 05:40 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    fclose(file_pointer); /* 変数名を file_pointer に変更 */
if文で定義しました。

2024-09-04 05:41 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    fclose(file_pointer); /* 変数名を file_pointer に変更 */
承知いたしました。

2024-09-04 05:41 UTC, riotakenouchi commented on exercise11/result11.txt
> +usage
承知いたしました。

2024-09-04 05:41 UTC, riotakenouchi commented on exercise11/result11.txt
> +$ echo -e "こんにちは、これはサンプルテキストファイルです。\nこのファイルはcプログラムで表示されます。
削除しました。

2024-09-04 05:42 UTC, riotakenouchi commented on exercise11/result11.txt
> +<テキストファイル実行結果>
上記を削除し、テキストファイルを実行した.txtをsample.txtという名前で追加しました。

2024-09-04 06:10 UTC, ShunsukeNakamura2 requested changes

2024-09-04 06:10 UTC, ShunsukeNakamura2 commented on exercise11/practice_11.c
> +    const char *input_filename = argv[1];
argcのチェックを行う前にargvを参照しないでください

2024-09-04 06:10 UTC, ShunsukeNakamura2 commented on exercise11/practice_11.c
> +    while (fgets(buffer, sizeof(buffer), fp) != NULL) {
fgets()もエラーになる場合があります。

2024-09-04 06:10 UTC, ShunsukeNakamura2 commented on exercise11/practice_11.c
> +    if (fclose(fp) != 0) {
このように書いてしまうと、デバッグやテスト時に、
「変数に任意の値を設定してifの中に入る」
ということができなくなります。

2024-09-04 06:10 UTC, ShunsukeNakamura2 commented on exercise11/result11.txt
> +usage: display_file filename
正常系の実行結果を追加してください

2024-09-04 06:40 UTC, ShotaNagao commented on exercise11/practice_11.c
> +#define BUFFER_SIZE 256  /* バッファのサイズを定義 */
1回のfgetsで何バイト読もうとしてますか？
もし256なら間違いです。
255なら大丈夫ですけど、多分意図としては違うと思います。

2024-09-04 06:40 UTC, ShotaNagao commented on exercise11/practice_11.c
> +#define BUFFER_SIZE 256  /* バッファのサイズを定義 */
BUFFER_SIZEは命名としては微妙だと思います。
BUFFERって何のバッファーなのか分からないからです。

コード上の処理を見るとこれは、1回の読み込みで読み込める最大のバイト数を定義している値だと思います。
ですので、MAX_READ_BYTSなどで良いと思います。

2024-09-04 06:40 UTC, ShotaNagao commented on exercise11/practice_11.c
> +    char buffer[BUFFER_SIZE];
文字列の最後はヌル文字で終わることが前提なのは理解していると思います。
fgetsの仕様上、この書き方でも問題ありませんが、読む人が見ると少し怖い書き方になっています。

理由は、BUFFER_SIZEの定義の意図が、読み込む最大のバイト数の場合、ヌル文字で終わらないように見えてしまいます。
なので、[記号定数(defineした定数のこと) + 1]が安心する書き方になると思います。

2024-09-04 06:40 UTC, ShotaNagao commented on exercise11/practice_11.c
> +    while (fgets(buffer, sizeof(buffer), fp) != NULL) {
fgetsの第二引数の型はintなので、それに合わせてください。

2024-09-04 06:40 UTC, ShotaNagao commented on exercise11/practice_11.c
> +    while (fgets(buffer, sizeof(buffer), fp) != NULL) {
第二引数には、ぱっと見で読み込む最大値が分かるといいと思います。
ヒントとしては、define値を使えばより読みやすいコードになると思います。
ただ、fgetsの仕様上、define値をそのまま書くと、想定よりも1バイト少ない値がセットされるので、書き方は工夫してください。

2024-09-05 05:18 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    const char *input_filename = argv[1];
if文でargcのチェックを行いました。

2024-09-05 05:19 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    if (fclose(fp) != 0) {
fcloseの結果を変数に格納しました。

2024-09-05 05:19 UTC, riotakenouchi commented on exercise11/result11.txt
> +usage: display_file filename
追加しました。

2024-09-05 05:19 UTC, riotakenouchi commented on exercise11/practice_11.c
> +#define BUFFER_SIZE 256  /* バッファのサイズを定義 */
255に修正しました。

2024-09-05 05:19 UTC, riotakenouchi commented on exercise11/practice_11.c
> +#define BUFFER_SIZE 256  /* バッファのサイズを定義 */
承知しました。

2024-09-05 05:20 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    char buffer[BUFFER_SIZE];
承知しました。

2024-09-05 05:20 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    while (fgets(buffer, sizeof(buffer), fp) != NULL) {
intを追加しました。

2024-09-05 05:20 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    while (fgets(buffer, sizeof(buffer), fp) != NULL) {
承知しました。

2024-09-05 05:37 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    while (fgets(buffer, sizeof(buffer), fp) != NULL) {
修正できていなかったのでRetry4で再度修正してpushしました。

2024-09-05 06:06 UTC, ShotaNagao commented on exercise11/practice_11.c
> +    /* ファイルのポインタとバッファを宣言 */
このコメントはいりません

2024-09-05 06:06 UTC, ShotaNagao commented on exercise11/practice_11.c
> +    const char *input_filename;
宣言部と処理部では改行を入れてください

2024-09-05 06:06 UTC, ShotaNagao commented on exercise11/practice_11.c
> +    input_filename = argv[1];  /* 引数を参照 */
中村さんの指摘に答えていないです。
もう少し考えてみてください。

2024-09-05 06:06 UTC, ShotaNagao commented on exercise11/practice_11.c
> +                fclose(fp);  /* エラー時はファイルを閉じる */
ここでfcloseは登場させない方が良いです。理由は下記。
・fcloseは二回行ってはいけないため、クロージングは一か所でまとめて行うことが望ましい。
・単純に下にfcloseの処理があるので冗長である。

どうすればまとめられるかは少し考えてみてください。

2024-09-05 06:06 UTC, ShotaNagao commented on exercise11/practice_11.c
> +                fclose(fp);  /* エラー時はファイルを閉じる */
上の指摘に対応したら意味のない指摘ですが、以前中村さんが指摘した通り、fcloseも失敗することがあります。

2024-09-05 06:06 UTC, ShotaNagao commented on exercise11/practice_11.c
> +    int close_result = fclose(fp);  /* fcloseの結果を変数に格納 */
ここで宣言した意味はありますか？

2024-09-05 06:06 UTC, ShotaNagao commented on exercise11/practice_11.c
> +    int close_result = fclose(fp);  /* fcloseの結果を変数に格納 */
変数名が分かりにくいです。
この変数名だと何かの結果を閉じるという意味になってます。

結果を閉じるという意味を持たせるなら、「何の」という情報を載せましょう。ただ、この方針だとどう頑張っても意味が伝わり切らない変数名になると思います。

思考を切り替えて、ここでの働きに注目してください。
fcloseの戻り値を入れてるだけです。
なので、returnからとってretで十分だと思います。(retで機能は十分伝わるので、「何の」という情報は特に必要ありません)

2024-09-05 06:06 UTC, ShotaNagao commented on exercise11/practice_11.c
> +    char buffer[MAX_READ_BYTES + 1];  /* ヌル文字分を考慮してサイズを定義 */
+ 1という表記でヌル文字を考慮していると読み取れるのでコメントは必要ありません。

2024-09-05 06:06 UTC, ShotaNagao commented on exercise11/practice_11.c
> +        /* 読み込んだ文字列を表示 */
このコメントもなくていいです。

2024-09-05 06:31 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    /* ファイルのポインタとバッファを宣言 */
修正しました。

2024-09-05 06:32 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    const char *input_filename;
改行を入れました。

2024-09-05 06:33 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    int close_result = fclose(fp);  /* fcloseの結果を変数に格納 */
特にありません。
ブロック冒頭にretを宣言して指摘を受けた場所にfcloseの処理を追加しました。

2024-09-05 06:33 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    int close_result = fclose(fp);  /* fcloseの結果を変数に格納 */
承知しました。

2024-09-05 06:34 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    char buffer[MAX_READ_BYTES + 1];  /* ヌル文字分を考慮してサイズを定義 */
修正しました。

2024-09-05 06:34 UTC, riotakenouchi commented on exercise11/practice_11.c
> +        /* 読み込んだ文字列を表示 */
修正しました。

2024-09-05 06:35 UTC, riotakenouchi commented on exercise11/practice_11.c
> +                fclose(fp);  /* エラー時はファイルを閉じる */
fcloseをファイルを閉じる処理の部分で1つにまとめました。

2024-09-05 06:35 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    input_filename = argv[1];  /* 引数を参照 */
argvを参照する場所を変更しました。

2024-09-05 06:36 UTC, riotakenouchi commented on exercise11/practice_11.c
> +                fclose(fp);  /* エラー時はファイルを閉じる */
承知しました。

2024-09-05 06:49 UTC, ShotaNagao commented on exercise11/practice_11.c
> +
この改行は必要ないです

2024-09-05 06:49 UTC, ShotaNagao commented on exercise11/practice_11.c
> +
ここも改行いらないです

2024-09-05 06:57 UTC, ShotaNagao commented on exercise11/practice_11.c
> +    ret = fclose(fp);  /* fcloseの結果を変数に格納 */
一応ですが、今のコードだとfp == NULLの場合でもfcloseが無条件で実施されてしまうので、fp != NULLという条件で実施するように変更してください。

2024-09-05 07:08 UTC, riotakenouchi commented on exercise11/practice_11.c
> +
修正しました。

2024-09-05 07:09 UTC, riotakenouchi commented on exercise11/practice_11.c
> +
修正しました。

2024-09-05 07:09 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    ret = fclose(fp);  /* fcloseの結果を変数に格納 */
変更しました。

2024-09-05 07:12 UTC, ShotaNagao commented on exercise11/practice_11.c
> +            if (feof(fp)) {
五月雨式の指摘ですみません。
feofの終了が正常値では特に何もしないでbreakするのであれば、feofの終了が異常の時の処理だけ書いて、そのあとまとめてbreakすれば処理が見やすくなると思います。

2024-09-05 07:27 UTC, riotakenouchi commented on exercise11/practice_11.c
> +            if (feof(fp)) {
処理をまとめました。

2024-09-05 07:49 UTC, ShotaNagao commented on exercise11/practice_11.c
> +                break;  /* エラー発生時にループを抜ける */
このif文で抜けたところでbreakしているのでここのbreakは不要です。

2024-09-05 07:54 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    while (fgets(buffer, sizeof(buffer), fp) != NULL) {
削除しました。

2024-09-05 07:57 UTC, ShotaNagao approved these changes

2024-09-05 07:57 UTC, riotakenouchi commented on exercise11/practice_11.c
> +                break;  /* エラー発生時にループを抜ける */
breakを削除しました。

2024-09-06 04:27 UTC, Ryusei-Ami requested changes
指摘内容について不明点がありましたら、Slackでご相談下さい。

2024-09-06 04:27 UTC, Ryusei-Ami commented on exercise11/practice_11.c
> +        return EXIT_FAILURE;
EXIT_xxマクロはexit()関数用に定義された関数なので、別の用途で使用してはいけません。
戻り値をマクロするのであれば、このプログラム用に別途定義して下さい。

2024-09-06 04:27 UTC, Ryusei-Ami commented on exercise11/practice_11.c
> +        perror("Error opening file");
ファイルオープンエラーは、オープンできない理由も出力して下さい。
製品運用の場合、理由が表示されれば対処も容易になリます。

2024-09-06 04:27 UTC, Ryusei-Ami commented on exercise11/practice_11.c
> +    while (1) {
安易に無限ループを使用しないで下さい。
無限ループは、他に手段がない場合やそれ以外の手段だと処理が尋常じゃなく複雑になる場合を除き、使用しない癖をつけて下さい。

2024-09-06 04:27 UTC, Ryusei-Ami commented on exercise11/practice_11.c
> +        if (fgets(buffer, (int)(MAX_READ_BYTES + 1), fp) == NULL) {
マクロの値は、可能ならばそのまま使用できることが望ましいです。
MAX_READ_BYTESとして定義する値は、そのまま利用できないか再考して下さい。
あと、不要なキャストは不要では？（キャストする前に、何故必要なのかを再考してみて下さい）。

2024-09-06 04:27 UTC, Ryusei-Ami commented on exercise11/practice_11.c
> +#define MAX_READ_BYTES 255  /* 読み込み最大バイト数を定義 */
ファイルの読み込み用バッファサイズであれば、ページサイズの倍数が望ましいです。
製品のソースだとしたら、255は明確な理由がない限りやめたほうが良いです。

2024-09-06 04:27 UTC, Ryusei-Ami commented on exercise11/result11.txt
> +$gcc -o display_file practice_11.c
課題番号も10を超えたので、そろそろMakefileを使うビルドに挑戦してみて下さい。

2024-09-06 05:08 UTC, Ryusei-Ami commented on exercise11/practice_11.c
> +    ret = fclose(fp);  /* fcloseの結果を変数に格納 */
fclose()は、「常に実施」「正常時のみ実施」の2択があります。
最終的に選んだ選択について、その理由を回答お願いします。

2024-09-09 06:18 UTC, ShotaNagao commented on exercise11/Makefile
> +# 出力ファイル名
出力ファイルがぱっと見で何を指すのか分かりにくい気がします。

ここにコメントをするなら作成する実行ファイルと明確に記載した方がいいと思います。

2024-09-09 06:18 UTC, ShotaNagao commented on exercise11/Makefile
> +OUTPUT = display_file
実行ファイルとするならPROGRAMがいいかと思います。

2024-09-09 06:18 UTC, ShotaNagao commented on exercise11/Makefile
> +	$(CC) $(CFLAGS) -o $(OUTPUT) $(SOURCES)
引数の指定として、見やすい順序は原則
(プログラム名) (inputする引数) (outputする引数)
だと思います。
ですので、-oのオプションは最後に持って行くのがいいかと思います。
これだと最終産物がぱっと見でpractice_11.cができるのかと思ってしまいます。

2024-09-09 06:18 UTC, ShotaNagao commented on exercise11/Makefile
> +	rm -f $(OUTPUT)
今回はプログラムが簡潔なため、ソースファイルと実行ファイルが1対1対応しているので、この書き方でも問題なく対象を削除できます。

ただ、ソースファイルと実行ファイルが1対1対応するとは限りません。
汎用的なソースファイルを作成すれば、いくつかの実行ファイルで共有されますし、1つの実行ファイルのために複数のソースファイルが必要になることもあります。
そういったときはオブジェクトファイル(.o)を明示的に作成します。
今回でもオブジェクトファイルがあっても問題なく削除できる形で書いて欲しいです。

2024-09-09 06:18 UTC, ShotaNagao commented on exercise11/Makefile
> +SOURCES = practice_11.c
オブジェクトファイル(.o)から実行ファイルを作成するような書き方にしてください。

2024-09-09 06:35 UTC, Ryusei-Ami commented on exercise11/Makefile
> +	$(CC) $(CFLAGS) -o $(OUTPUT) $(SOURCES)
> 引数の指定として、見やすい順序は原則
> (プログラム名) (inputする引数) (outputする引数)
> だと思います。
（プログラム名）（オプション）（ターゲット＝オプション無し引数）
という書き方も一般的なので、私としてはどちらでも良いです。
どちらでも正解なので、既存のつくりやチームの方針にあっていれば良いとの認識です。

2024-09-09 06:43 UTC, ShotaNagao commented on exercise11/Makefile
> +	$(CC) $(CFLAGS) -o $(OUTPUT) $(SOURCES)
@Ryusei-Ami 
承知しました。武ノ内さんと少し会話して認識合わせをします。
認識のすり合わせが出来次第、武ノ内さんから今後の書き方をこちらのコメントに返信させていただきます。

2024-09-10 01:39 UTC, riotakenouchi commented on exercise11/Makefile
> +	$(CC) $(CFLAGS) -o $(OUTPUT) $(SOURCES)
長尾さんと相談した結果以下のように認識を合わせました。

・トレーナーと相談して上記の書き方に統一することにした
・これ以降のMakefileの書き方で上記の順序でない場合は指摘の対象とする

2024-09-10 04:31 UTC, ShunsukeNakamura2 commented on exercise11/Makefile
> +CFLAGS = -Wall -Wextra -O2
最適化のレベルに2を指定している理由はありますか？
指摘ではなく単純に質問です。
会話を見落としていたらすみません。

2024-09-10 04:46 UTC, riotakenouchi commented on exercise11/Makefile
> +CFLAGS = -Wall -Wextra -O2
コードサイズの影響を抑えると同時にレベル1よりもリソースの効率性が高いということが調べていくうちに分かったので使用しました。

2024-09-10 05:01 UTC, ShunsukeNakamura2 commented on exercise11/Makefile
> +CFLAGS = -Wall -Wextra -O2
回答ありがとうございます。
承知しました。

2024-09-10 05:02 UTC, ShunsukeNakamura2 approved these changes

2024-09-10 05:12 UTC, riotakenouchi commented on exercise11/practice_11.c
> +        return EXIT_FAILURE;
defineで定義したものを使用するように変更しました。

2024-09-10 05:15 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    while (1) {
while文を修正しました。

2024-09-10 05:18 UTC, riotakenouchi commented on exercise11/practice_11.c
> +        if (fgets(buffer, (int)(MAX_READ_BYTES + 1), fp) == NULL) {
MAX_READ_BYTES を直接利用し、不要なキャストを削除しました。

2024-09-10 05:18 UTC, riotakenouchi commented on exercise11/practice_11.c
> +#define MAX_READ_BYTES 255  /* 読み込み最大バイト数を定義 */
255から384に変更しました。

2024-09-10 05:18 UTC, riotakenouchi commented on exercise11/result11.txt
> +$gcc -o display_file practice_11.c
Makefileをpushしました。

2024-09-10 05:31 UTC, riotakenouchi commented on exercise11/practice_11.c
> +        perror("Error opening file");
修正できていなかったのでRetry10にて修正いたしました。

2024-09-10 05:33 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    ret = fclose(fp);  /* fcloseの結果を変数に格納 */
「常に実施」を選択しました。

理由といたしましては
・fpがNULLになることはない点
・NULL判定をfcloseの前でする必要がない点
上記２点を考慮したためです

2024-09-10 05:34 UTC, riotakenouchi commented on exercise11/Makefile
> +OUTPUT = display_file
修正しました。

2024-09-10 05:34 UTC, riotakenouchi commented on exercise11/Makefile
> +	rm -f $(OUTPUT)
修正しました。

2024-09-10 05:34 UTC, riotakenouchi commented on exercise11/Makefile
> +SOURCES = practice_11.c
修正しました。

2024-09-10 06:24 UTC, Ryusei-Ami requested changes
MakefileはOKです。
ソースの指摘があるので、修正お願いします。

2024-09-10 06:24 UTC, Ryusei-Ami commented on exercise11/practice_11.c
> +#define MAX_READ_BYTES 384  /* 読み込み最大バイト数を定義（ページサイズの倍数） */
384がページサイズの倍数と認識しているということは、「ページサイズ」の意味が正しく理解できていないように見受けられます。再確認お願いします。

2024-09-10 06:24 UTC, Ryusei-Ami commented on exercise11/practice_11.c
> +    while (fgets(buffer, MAX_READ_BYTES + 1, fp) != NULL) {
この書き方だと、bufferのサイズが変わったときにfgets()の第二引数の修正も必要になり、保守性が下がります。

2024-09-10 06:24 UTC, Ryusei-Ami commented on exercise11/practice_11.c
> +        fclose(fp);  /* エラー時でも必ずファイルを閉じる */
closeやfree等の終了処理は、正常系と異常系で共通になるのが望ましいです。
エラー処理が増えると各return処理の前に終了処理が必要になり、終了処理で実行する関数が多くなるとバグの温床になります。

2024-09-10 06:24 UTC, Ryusei-Ami commented on exercise11/practice_11.c
> +    if (fclose(fp) != 0) {
> fcloseの結果を変数に格納しました。

対処漏れですか？

2024-09-10 07:02 UTC, Ryusei-Ami commented on exercise11/practice_11.c
> +    ret = fclose(fp);  /* fcloseの結果を変数に格納 */
選択理由について、問題ないことを確認しました。

2024-09-11 01:31 UTC, riotakenouchi commented on exercise11/practice_11.c
> +#define MAX_READ_BYTES 384  /* 読み込み最大バイト数を定義（ページサイズの倍数） */
256に変更しました。

2024-09-11 01:32 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    while (fgets(buffer, MAX_READ_BYTES + 1, fp) != NULL) {
MAX_READ_BYTES を使用して定義した定数を再利用する方法に修正しました。

2024-09-11 01:33 UTC, riotakenouchi commented on exercise11/practice_11.c
> +        fclose(fp);  /* エラー時でも必ずファイルを閉じる */
cleanup 関数の追加を行い正常系・異常系両方の終了処理において、cleanup 関数を呼び出すようにしました。

2024-09-11 01:35 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    if (fclose(fp) != 0) {
retという変数に格納していたのですが、makeコマンドを実行したときにretの部分がエラーになっていたので削除してしまっていました。

再度変数retを定義し格納しました。(makeコマンドで実行した場合でもコンパイルすることができました。)

2024-09-12 01:30 UTC, ShunsukeNakamura2 requested changes

2024-09-12 01:30 UTC, ShunsukeNakamura2 commented on exercise11/practice_11.c
> +    char buffer[MAX_READ_BYTES + 1];
MAX_READ_BYTES をページサイズにしたのに、ここで+1してしまうと1ページに乗らなくなると思います

2024-09-12 01:30 UTC, ShunsukeNakamura2 commented on exercise11/practice_11.c
> +    if (fp != NULL) {
この時点でfp == NULL になるのはあり得ないので不要な判定です

2024-09-12 01:30 UTC, ShunsukeNakamura2 commented on exercise11/practice_11.c
> +    return ret;  /* 正常終了またはエラーを返す */
意図した値のretがreturn できてますか？
fgets() に失敗し、かつfclose()に成功したパターンが怪しいです。

2024-09-12 02:03 UTC, ShotaNagao commented on exercise11/practice_11.c
> +        ret = fclose(fp);
retはmain関数の戻り値として使われているので、ここはまた別変数で受けると良いと思います。

2024-09-12 04:48 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    return ret;  /* 正常終了またはエラーを返す */
修正しました。

2024-09-12 04:48 UTC, riotakenouchi commented on exercise11/practice_11.c
> +        ret = fclose(fp);
close_retという変数に格納しました。

2024-09-12 04:49 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    if (fp != NULL) {
削除しました。

2024-09-12 04:49 UTC, riotakenouchi commented on exercise11/practice_11.c
> +    char buffer[MAX_READ_BYTES + 1];
修正しました。

2024-09-12 05:00 UTC, ShunsukeNakamura2 approved these changes

2024-09-12 05:30 UTC, Ryusei-Ami approved these changes

2024-09-12 05:33 UTC, merged