課題12のコードと実行結果
riotakenouchi/C_charenge pull request #15
Opened 2024-09-18 07:26 UTC by riotakenouchi

パラメータで渡されたファイルの16進ダンプを
表示するプログラムを作成してください。

usage
usage: プログラム名 filename
options: filename ファイル名

出力例：
$ ADDRESS 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
$ 00000000 01 02 03 41 42 43 20 5C 26 82 A0 83 41 B1 B2 82
$ 00000100 A2

2024-09-24 01:49 UTC, ShunsukeNakamura2 requested changes

2024-09-24 01:49 UTC, ShunsukeNakamura2 commented on exercise12/result12.txt
> +$ ./headump
makefileは「a.out」
実行結果は「hexdump」と「headump」
どれが本物でしょうか。

2024-09-24 01:49 UTC, ShunsukeNakamura2 commented on exercise12/result12.txt
> +00000570: 7572 6e20 5355 4343 4553 533b 0a7d 0a    urn SUCCESS;.}.
hexdumpで表示させたファイルと内容が違ってそうです。
プログラム書き換えて、実行結果は更新してない？
エビデンスなので揃えてください。

2024-09-24 01:49 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> + * @param file 読み込むファイルへのポインタ。
fileは[in]、[out]、[in,out]どれでしょうか。

2024-09-24 01:49 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +void print_hex_dump(FILE *file)
プロトタイプ宣言をしてください

2024-09-24 01:49 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +	size_t j;
干渉しないならば、iを使いまわしても大丈夫です。

2024-09-24 01:49 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +	printf("\n");
26行～30行目までのprintf()は一回のprintf()にまとめてください

2024-09-24 01:49 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +	while ((bytes_read = fread(buffer, sizeof(unsigned char),
fread()のエラーハンドリングを追加してください

2024-09-24 01:49 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +		printf("\n");
36行～46行目までのprintf()は一回のprintf()にまとめてください

2024-09-24 01:49 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +			if (j < bytes_read) {
for文の終了条件を適切に設定すると、ここのif判定は要らなくなると思います。

2024-09-24 01:49 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +		fprintf(stderr, "options: filename  ファイル名\n");
ここのfprintf()は一つにまとめられそうです。

2024-09-24 01:49 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +		perror("Error opening file");
openに失敗したファイル名も、エラーメッセージに書いてください

2024-09-24 01:49 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +	fclose(file);
fclose()のエラーハンドリングを追加してください

2024-09-24 01:49 UTC, ShunsukeNakamura2 commented on exercise12/result12.txt
> +ADDRESS 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
出力例がこうなっていたからだと思いますが、
ADDRESS
の後ろにもう一つスペースを追加してください。
下と揃っていた方が見やすいです。

2024-09-24 07:46 UTC, riotakenouchi commented on exercise12/result12.txt
> +$ ./headump
hexdumpです

2024-09-24 07:46 UTC, riotakenouchi commented on exercise12/practice_12.c
> + * @param file 読み込むファイルへのポインタ。
inに修正しました。

2024-09-25 00:42 UTC, ShotaNagao commented on exercise12/practice_12.c
> +	unsigned long address = 0;
addressというよりindexが正しいかと思います。
配列のインデックスで検索するとイメージつかめるかと思います。

2024-09-25 01:28 UTC, riotakenouchi commented on exercise12/result12.txt
> +00000570: 7572 6e20 5355 4343 4553 533b 0a7d 0a    urn SUCCESS;.}.
承知いたしました。

2024-09-25 01:28 UTC, riotakenouchi commented on exercise12/practice_12.c
> +void print_hex_dump(FILE *file)
宣言を行いました。

2024-09-25 01:29 UTC, riotakenouchi commented on exercise12/practice_12.c
> +	size_t j;
変更いたしました。

2024-09-25 01:29 UTC, riotakenouchi commented on exercise12/practice_12.c
> +			if (j < bytes_read) {
削除しました。

2024-09-25 01:29 UTC, riotakenouchi commented on exercise12/practice_12.c
> +		fprintf(stderr, "options: filename  ファイル名\n");
1つにまとめました。

2024-09-25 01:29 UTC, riotakenouchi commented on exercise12/practice_12.c
> +		perror("Error opening file");
記述しました。

2024-09-25 01:29 UTC, riotakenouchi commented on exercise12/practice_12.c
> +	fclose(file);
追加しました。

2024-09-25 01:30 UTC, riotakenouchi commented on exercise12/practice_12.c
> +	unsigned long address = 0;
承知いたしました。

2024-09-25 01:31 UTC, riotakenouchi commented on exercise12/result12.txt
> +ADDRESS 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
スペースを追加しました。

2024-09-25 01:33 UTC, riotakenouchi commented on exercise12/result12.txt
> +ADDRESS 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
スペースを追加したのですが、出力例が変わっていないように見えるのは気のせいでしょうか？

2024-09-25 02:37 UTC, ShunsukeNakamura2 requested changes

2024-09-25 02:37 UTC, ShunsukeNakamura2 commented on exercise12/result12.txt
> +ADDRESS 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
出力結果変わってないですね。
少し原因を考えてみて下さい。
どうしても分からなければ聞いてください（そこまで時間を使うような内容じゃないので）

2024-09-25 02:37 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +        for (; i < BYTE_PER_LINE; i++) {
足りない部分をスペースで埋めるような要件は無かったと思いますが、このようにしている理由がありますか？

2024-09-25 02:37 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +    if (fclose(file) != 0) {
一度変数で受け取ってください

2024-09-25 02:37 UTC, ShunsukeNakamura2 commented on exercise12/result12.txt
> +usage: ./headump filename
argv[0]を出してるのに
usage: ./headump filename
が出てきます？

2024-09-25 02:37 UTC, ShunsukeNakamura2 commented on exercise12/result12.txt
> +usage: ./headump filename
usageでは「./」を消してください

2024-09-25 02:58 UTC, riotakenouchi commented on exercise12/practice_12.c
> +        for (; i < BYTE_PER_LINE; i++) {
そちらの方が見やすいと考えました。

2024-09-25 03:04 UTC, riotakenouchi commented on exercise12/result12.txt
> +usage: ./headump filename
承知いたしました。

2024-09-25 03:04 UTC, riotakenouchi commented on exercise12/result12.txt
> +usage: ./headump filename
Makefileの記述に誤りがありました。

2024-09-25 03:04 UTC, riotakenouchi commented on exercise12/practice_12.c
> +    if (fclose(file) != 0) {
close_retという変数に格納しました。

2024-09-25 03:23 UTC, riotakenouchi commented on exercise12/result12.txt
> +ADDRESS 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
Makefileを修正いたしました。

2024-09-25 06:09 UTC, riotakenouchi commented on exercise12/practice_12.c
> +	printf("\n");
1つにまとめました。

2024-09-25 06:10 UTC, riotakenouchi commented on exercise12/practice_12.c
> +	while ((bytes_read = fread(buffer, sizeof(unsigned char),
追加しました。

2024-09-25 06:10 UTC, riotakenouchi commented on exercise12/practice_12.c
> +		printf("\n");
1つにまとめました。

2024-09-25 08:47 UTC, ShotaNagao commented on exercise12/practice_12.c
> +void print_hex_dump(FILE *file)
関数の中でエラーハンドリングしていますが、戻り値の認識を聞きたいです。
今のprint_hex_dumpは必ず正常終了として処理する流れだと思いますが、ファイルの読み込みエラーはどうします？
今のままだと読み込みエラーが生じてもmainは正常終了になりますが、想定通りの設計でしょうか。

2024-09-25 08:47 UTC, ShotaNagao commented on exercise12/practice_12.c
> +		/* アドレスの表示 */
インデックス？

2024-09-25 08:47 UTC, ShotaNagao commented on exercise12/practice_12.c
> +		printf("%08lX ", index);
下の処理で出力するhex表記の配列を作っているのであれば、インデックスとhex表記をまとめた配列にすれば、printfの使用回数が下がるのでは？

2024-09-25 08:47 UTC, ShotaNagao commented on exercise12/practice_12.c
> +	size_t i;  /* ここで宣言 */
ここで宣言に重要な意味がありますか？

2024-09-25 08:47 UTC, ShotaNagao commented on exercise12/practice_12.c
> +		return FAILURE;  /* エラー理由の出力 */
コメントの位置は正しいでしょうか。
また、重要なコメントでしょうか。
改めて考えてみてください。

2024-09-25 08:47 UTC, ShotaNagao commented on exercise12/practice_12.c
> +		offset += sprintf(header + offset, "%02lX ", (unsigned long)i);
第一引数はもっといい書き方があると思います。
64行目の処理をもう少し考えればここの書き方ももう少し分かりやすい書き方になるかと思います。

2024-09-25 08:47 UTC, ShotaNagao commented on exercise12/practice_12.c
> +	size_t offset = 0;
このコードの使い方的にchar *で使用した方が分かりやすいコードになるのでは？
例えば、
```
char *offset = header;
offset++
```
とするとoffsetはheader[1]を指すポインタになっています。参考にしてください。

2024-09-25 23:24 UTC, ShunsukeNakamura2 requested changes

2024-09-25 23:24 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> + * @param file [in] 読み込むファイルへのポインタ。
[in]の書き方適切でしょうか。
過去の課題を見返してみてください

2024-09-25 23:24 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +	char header[256];
ヘッダー行も他のダンプ行と同じ長さなのでは？

2024-09-25 23:24 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +		offset += sprintf(header + offset, "%02lX ", (unsigned long)i);
64行目で書いた"ADDRESS  "を上書きしてません？
出力結果、提出前にちゃんと確認しました？

2024-09-25 23:24 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +	sprintf(header, "ADDRESS  ");
"ADDRESS  "はheaderに書き込まなくても、64行目で
printf("ADDRESS  %s\n", header);
とすれば良い気もします。どうするかはお任せします。

2024-09-25 23:24 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +		offset += sprintf(header + offset, "%02lX ", (unsigned long)i);
offsetを導入しなくても、iだけで望みの動作を実現できると思います。

2024-09-25 23:24 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +	while ((bytes_read = fread(buffer, sizeof(unsigned char), BYTE_PER_LINE, file)) > 0) {
戻り値が0の時もエラーの可能性があると思います

2024-09-25 23:24 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +		if (bytes_read < BYTE_PER_LINE && ferror(file)) {
前半のチェックは不要では？

2024-09-25 23:24 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +		printf("%08lX ", index);
末尾は0固定なので
```
79|        printf("%07lX0 ", index);
・・・
89|        index++;
```
とすれば、indexの消費量を1/16に抑えることができます。

2024-09-25 23:24 UTC, ShunsukeNakamura2 commented on exercise12/result12.txt
> +ADDRESS  00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
今のプログラムで"ADDRESS  "ってちゃんと出てきますか？

2024-09-26 00:19 UTC, riotakenouchi commented on exercise12/practice_12.c
> +	size_t i;  /* ここで宣言 */
特にありません。削除いたします。

2024-09-26 00:19 UTC, riotakenouchi commented on exercise12/practice_12.c
> +		return FAILURE;  /* エラー理由の出力 */
承知いたしました。

2024-09-26 05:15 UTC, riotakenouchi commented on exercise12/practice_12.c
> +void print_hex_dump(FILE *file)
想定通りではないので修正いたします。

2024-09-26 05:17 UTC, riotakenouchi commented on exercise12/practice_12.c
> +		offset += sprintf(header + offset, "%02lX ", (unsigned long)i);
承知いたしました。

2024-09-26 07:49 UTC, riotakenouchi commented on exercise12/practice_12.c
> +		printf("%08lX ", index);
承知しました。

2024-09-26 07:49 UTC, riotakenouchi commented on exercise12/practice_12.c
> +		offset += sprintf(header + offset, "%02lX ", (unsigned long)i);
修正しました。

2024-09-26 09:02 UTC, riotakenouchi commented on exercise12/practice_12.c
> +		printf("%08lX ", index);
承知しました。

2024-09-26 09:03 UTC, riotakenouchi commented on exercise12/result12.txt
> +ADDRESS  00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
修正しました。

2024-09-26 09:03 UTC, riotakenouchi commented on exercise12/practice_12.c
> +		if (bytes_read < BYTE_PER_LINE && ferror(file)) {
修正しました。

2024-09-26 09:03 UTC, riotakenouchi commented on exercise12/practice_12.c
> +	while ((bytes_read = fread(buffer, sizeof(unsigned char), BYTE_PER_LINE, file)) > 0) {
修正しました。

2024-09-26 09:03 UTC, riotakenouchi commented on exercise12/practice_12.c
> +		offset += sprintf(header + offset, "%02lX ", (unsigned long)i);
修正しました。

2024-09-26 09:04 UTC, riotakenouchi commented on exercise12/practice_12.c
> +	sprintf(header, "ADDRESS  ");
修正しました。

2024-09-26 09:04 UTC, riotakenouchi commented on exercise12/practice_12.c
> +		offset += sprintf(header + offset, "%02lX ", (unsigned long)i);
申し訳ございません。修正し、確認いたしました。

2024-09-26 09:04 UTC, riotakenouchi commented on exercise12/practice_12.c
> +	char header[256];
守勢しました。

2024-09-26 09:05 UTC, riotakenouchi commented on exercise12/practice_12.c
> +	char header[256];
修正しました。

2024-09-26 09:05 UTC, riotakenouchi commented on exercise12/practice_12.c
> + * @param file [in] 読み込むファイルへのポインタ。
承知いたしました。

2024-09-26 10:23 UTC, ShunsukeNakamura2 requested changes

2024-09-26 10:23 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +
細かいですが、この2つ目の改行要らないです

2024-09-26 10:23 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +	  	 return ret;
インデント適切に

2024-09-26 10:23 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +	  	 return ret;
ここでreturn すると、ファイルが閉じられないのでは？

2024-09-26 10:23 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> + * @param file [in] 読み込むファイルへのポインタ。
もう一度確認をお願いします。

2024-09-26 10:23 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +		printf("%07lX0 ", index);
86行目のprintf()とくっつけられそうです

2024-09-26 10:23 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +		if ( ferror(file)) {
細かいですが、ferror()の前のスペース不要です

2024-09-26 10:23 UTC, ShunsukeNakamura2 commented on exercise12/result12.txt
> +[takenouchi@vzr93001 exercise12]$
細かいですが、要らない行なのでついでに消しといてください

2024-09-27 00:09 UTC, riotakenouchi commented on exercise12/practice_12.c
> +
承知いたしました。

2024-09-27 00:10 UTC, riotakenouchi commented on exercise12/practice_12.c
> +	  	 return ret;
承知しました。

2024-09-27 00:11 UTC, riotakenouchi commented on exercise12/practice_12.c
> +		if ( ferror(file)) {
承知いたしました。

2024-09-27 00:12 UTC, riotakenouchi commented on exercise12/result12.txt
> +[takenouchi@vzr93001 exercise12]$
承知いたしました。

2024-09-27 00:59 UTC, riotakenouchi commented on exercise12/practice_12.c
> +		printf("%07lX0 ", index);
承知いたしました。

2024-09-27 00:59 UTC, riotakenouchi commented on exercise12/practice_12.c
> +	  	 return ret;
修正いたしました。

2024-09-27 01:00 UTC, riotakenouchi commented on exercise12/practice_12.c
> + * @param file [in] 読み込むファイルへのポインタ。
修正いたしました。

2024-09-27 01:20 UTC, ShunsukeNakamura2 requested changes

2024-09-27 01:20 UTC, ShunsukeNakamura2 commented on exercise12/practice_12.c
> +	 ret = print_hex_dump(file);
細かいですが、インデントおかしそうです。
うるさく言いますが、構造化プログラミングにおいてインデントは大事な要素なので注意してください。

2024-09-27 01:21 UTC, riotakenouchi commented on exercise12/practice_12.c
> +	 ret = print_hex_dump(file);
承知いたしました。ご指摘ありがとうございます。

2024-09-27 01:37 UTC, ShunsukeNakamura2 approved these changes

2024-09-27 02:03 UTC, ShotaNagao commented on exercise12/practice_12.c
> +		sprintf(&line[3 * i] , "%02lX ", i);
ここの処理が少し難しく感じます。
3の意味は各バイトに2桁、スペース1桁の合計だという事は分かります。
ただ、これは変数の宣言部分で読み取って記憶する必要があるので、長いコードになればなるほど読み取りにくくなると思います。

ここはコメントで実例を出しつつ、何故3の倍数のところから配列を作っているのかを説明するといいと思います。

2024-09-27 02:03 UTC, ShotaNagao commented on exercise12/practice_12.c
> +		 	 sprintf(&line[3 * i], "%02X ", buffer[i]);
同上

2024-09-27 02:09 UTC, ShotaNagao commented on exercise12/practice_12.c
> + * @param[in] file 読み込むファイルへのポインタ。
returnの説明を追記してください。

2024-09-27 02:49 UTC, riotakenouchi commented on exercise12/practice_12.c
> + * @param[in] file 読み込むファイルへのポインタ。
追記いたします。

2024-09-27 02:50 UTC, riotakenouchi commented on exercise12/practice_12.c
> +		return FAILURE;  /* エラー理由の出力 */
削除いたします。

2024-09-27 03:31 UTC, ShotaNagao commented on exercise12/practice_12.c
> + * return 成功時にSUCCESSを、失敗時にFAILUREを返します。
@付けてください

2024-09-27 03:31 UTC, ShotaNagao commented on exercise12/practice_12.c
> +		/* 1バイトにつき、3つスペースを使うため、1文字はline[0]、2文字目はline[3]から書き込む */
1バイトではなく1文字では？
下記のようなことを言いたい？
/* 入力文字1文字につき、HEX表記の下2桁(0xXXのXX)を使用するため2 バイト、空白スペース(0x40)の1バイトの合計3バイトを使う。そのため入力文字の1文字目はline[0]から始まり2文字目以降の添え字は3の倍数から始まる。*/

2024-09-27 06:17 UTC, riotakenouchi commented on exercise12/practice_12.c
> +		/* 1バイトにつき、3つスペースを使うため、1文字はline[0]、2文字目はline[3]から書き込む */
失礼いたしました。そのように修正したいです。

2024-09-27 08:22 UTC, ShotaNagao approved these changes

2024-09-30 01:09 UTC, Ryusei-Ami requested changes
よく書けていると思います。
ロジックに関する指摘はありません。
細かい指摘のみですので、ご確認お願いします。

2024-09-30 01:09 UTC, Ryusei-Ami commented on exercise12/practice_12.c
> +		/* 入力文字1文字につき、HEX表記の下2桁(0xXXのXX)を使用するため2 バイト、半角スペースの1バイトの合計3バイトを使う。そのため入力文字の1文字		 目はline[0]から始まり2文字目以降の添え字は3の倍数となる。*/
コメントがみずらいので、適当な箇所で改行入れてほしいです。
類似箇所も同様。
以下、例。
```
/* 
 * 入力文字1文字につき、HEX表記の下2桁(0xXXのXX)を使用するため2 バイト、半角スペースの
 * 1バイトの合計3バイトを使う。そのため入力文字の1文字目はline[0]から始まり2文字目以降の
 * 添え字は3の倍数となる。
 */
```

2024-09-30 01:09 UTC, Ryusei-Ami commented on exercise12/practice_12.c
> +		fprintf(stderr, "usage: hexdump filename\noptions: filename ファイル名\n");
以下のように書いたほうが、改行が実際の表示イメージと合うので見やすいです。
（空白は適当なので、修正時は上下揃えてください）。
```
fprintf(stderr, "usage: hexdump filename\n"
                      "options: filename ファイル名\n");
```

2024-09-30 02:19 UTC, Ryusei-Ami approved these changes
お疲れ様でした。
修正内容について、問題ないことを確認しました。

2024-09-30 02:20 UTC, merged