char,short,int,longの配列とポインタを 定義し、それぞれ、配列の添字を1つ進めた 場合とポインタをインクリメントした場合に、 アドレスが何バイト進むか表示してください。  出力例：char 配列=1 short 配列=2 int 配列=4 long 配列=4 　charﾎﾟｲﾝﾀ=1 shortﾎﾟｲﾝﾀ=2 intﾎﾟｲﾝﾀ=4 longﾎﾟｲﾝﾀ=4
riotakenouchi/C_charenge pull request #8
Opened 2024-08-07 06:25 UTC by riotakenouchi

2024-08-08 06:08 UTC, ShunsukeNakamura2 requested changes

2024-08-08 06:08 UTC, ShunsukeNakamura2 commented on exercise5/practice_5.c
> +int main(void) {
関数定義の { は次の行に置いてください

2024-08-08 06:08 UTC, ShunsukeNakamura2 commented on exercise5/practice_5.c
> +    char char_array[10];
配列のサイズは2で十分なのでは

2024-08-08 07:00 UTC, ShotaNagao commented on exercise5/practice_5.c
> +    char char_array[10];
初期値に関しては入れるようにしてください。
製品によって定義時に入れている場合や初期化処理を別途書いている場合がありますが、初期値は入れています。
初期値は基本的に0x00で大丈夫です。

2024-08-08 07:00 UTC, ShotaNagao commented on exercise5/practice_5.c
> +    printf("charポインタ=%zu shortポインタ=%zu intポインタ=%zu longポインタ=%zu\n",
1個前のprintf()の処理と一緒にしなかった理由は何かありますでしょうか。
例えば、同じprintfでも各引数の計算は2パターンある(添え字を進めた場合とインクリメントした場合を明示的に分けたい)ので分けているとか、表示する行が2行なので2回分printf()をしたいなどでしょうか。

2024-08-08 07:00 UTC, ShotaNagao commented on exercise5/practice_5.c
> +
定義が続いているだけなのでここの空行は詰めて大丈夫です。

2024-08-08 08:14 UTC, ShunsukeNakamura2 requested changes

2024-08-08 08:14 UTC, ShunsukeNakamura2 commented on exercise5/practice_5.c
> +    char char_array[2] = 0x00;
これコンパイル通りました？

2024-08-09 01:32 UTC, ShunsukeNakamura2 requested changes

2024-08-09 01:32 UTC, ShunsukeNakamura2 commented on exercise5/practice_5.c
> +    char char_array[2] = "ab";
要素数Nのchar配列に入れる文字数はN-1文字までとしてください。
試しにchar_arrayをprintf()で表示してみてください。

2024-08-09 01:32 UTC, ShunsukeNakamura2 commented on exercise5/practice_5.c
> +    short short_array[2] = {1,2};
これでも間違いではありませんが、一括で0に初期化する方法があるので、それに書き換えてみてください。
要素数が10000だろうと一発で初期化できます。

2024-08-09 01:32 UTC, ShunsukeNakamura2 commented on exercise5/practice_5.c
> +}
最後に改行を入れてください

2024-08-13 00:56 UTC, ShunsukeNakamura2 approved these changes

2024-08-13 00:56 UTC, ShunsukeNakamura2 commented on exercise5/practice_5.c
> +    short short_array[2] = {};
= {0} が良く使用される書き方だと思いますが(少なくともDataMagicでは{0}と書いてます)、動作は私の知る限り同じなので修正はしなくて大丈夫です。
{0} という書き方があるということを覚えてもらえれば良いです。
担当製品の慣例に従ってください。

2024-08-13 00:56 UTC, ShunsukeNakamura2 commented on exercise5/practice_5.c
> +    char char_array[2] = "a";
char配列も = {0} の初期化をして問題ないです。
ただ今回の課題では0で初期化をすることが必要ではないので、修正は求めないです。

2024-08-13 01:36 UTC, ShotaNagao approved these changes

2024-08-13 07:34 UTC, merged