課題6のコードと実行結果
riotakenouchi/C_charenge pull request #9
Opened 2024-08-13 05:23 UTC by riotakenouchi

下記の構造体のサイズ、各メンバのサイズの合計、各メンバの先頭からのオフセットとサイズを表示してください。

構造体

struct SAMPLE_t
[
    char m1;
    short m2;
    char m3;
    long m4;
    char m5;
    void *m6;
};

出力例:
$構造体のサイズ=20 メンバの合計サイズ=13
$char  m1 オフセット=0 サイズ=1
$short m2 オフセット=2 サイズ=2
$char  m3 オフセット=4 サイズ=1
$long  m4 オフセット=8 サイズ=4
$char  m5 オフセット=12 サイズ=1
$void* m6 オフセット=16 サイズ=4

2024-08-13 06:00 UTC, ShunsukeNakamura2 requested changes

2024-08-13 06:00 UTC, ShunsukeNakamura2 commented on exercise6/practice_6.c
> +    size_t total_size = sizeof(char) + sizeof(short) + sizeof(char) + sizeof(long) + sizeof(char) + sizeof(void *);
SAMPLE_t のメンバのサイズを足してください（結果は変わりませんが）

2024-08-13 06:00 UTC, ShunsukeNakamura2 commented on exercise6/practice_6.c
> +    size_t total_size = sizeof(char) + sizeof(short) + sizeof(char) + sizeof(long) + sizeof(char) + sizeof(void *);
変数宣言はブロックの先頭で行ってください

2024-08-13 06:00 UTC, ShunsukeNakamura2 commented on exercise6/practice_6.c
> +            offsetof(struct SAMPLE_t, m1), sizeof(char),
ここもSAMPLE_t のメンバのサイズを表示してください（結果は変わりませんが）

2024-08-13 06:00 UTC, ShunsukeNakamura2 commented on exercise6/result6.txt
> +メンバの合計サイズ=17
出力例のように1行で表示してください

2024-08-13 08:02 UTC, ShotaNagao commented on exercise6/practice_6.c
> +    size_t total_size = sizeof(char) + sizeof(short) + sizeof(char) + sizeof(long) + sizeof(char) + sizeof(void *);
夕会後に話した内容を反映してください。

2024-08-14 01:43 UTC, ShunsukeNakamura2 requested changes

2024-08-14 01:43 UTC, ShunsukeNakamura2 commented on exercise6/practice_6.c
> + {
一応、構造体定義の { は次の行に置かなくていいです。
今回は問題文（仕様書）がそうなっていて、それに合わせてもらった形だと思うのでこれでOKです。
参考までに。

2024-08-14 01:43 UTC, ShunsukeNakamura2 commented on exercise6/practice_6.c
> +
細かいですが、ここと、
int main(void)
{
直後の改行は不要です。

2024-08-14 01:43 UTC, ShunsukeNakamura2 commented on exercise6/practice_6.c
> +    size_m1 = sizeof(sample.m1);
宣言と同時に代入しても良いと思います。

2024-08-14 01:43 UTC, ShunsukeNakamura2 commented on exercise6/practice_6.c
> +    printf("メンバの合計サイズ=%zu\n", total_size);
ここは出力が1行なので、printf()を分けないでください

2024-08-14 02:16 UTC, ShotaNagao commented on exercise6/practice_6.c
> +#include <stddef.h>  /*offsetof を使用するため定義*/
最初に断っておきますが、修正の必要はないです。

このコメントは何のためにヘッダーをインクルードしているか分かりやすくするためのコメントだと思いますが、個人的には無い方がいいかなと思います。下記に理由を述べます。

①エディタの機能でヘッダー定義は容易に確認できるので、わざわざコメント部分を読まない(ヘッダーの中身を直接確認する方が正確だし理解できる)
②標準ライブラリのヘッダーに関しては、定義一覧が容易に調べられる(ネット等で)
③自作のヘッダーに関しては、ヘッダー中にコメント等で説明を設けているのでわざわざインクルード側で説明する必要はない
④何らかの形でヘッダーの更新があった際に、インクルード側のコメントの内容と相違点が出る可能性がある
⑤二重インクルード対策は、基本中の基本かつヘッダー側で設ける仕様のため、インクルード側で特別意識することではない。(言い換えるとヘッダー作成時には絶対に意識して作成してください)

以上になります。参考程度に目を通してください。

2024-08-14 05:45 UTC, ShunsukeNakamura2 approved these changes

2024-08-14 05:50 UTC, ShotaNagao approved these changes

2024-08-14 05:51 UTC, merged